version: 2
jobs:
  test:
    working_directory: /go/src/github.com/hscasn/go-microservice
    docker:
      - image: circleci/golang:1.11
      - image: redis:4.0
    steps:
      - checkout
      - run: go get -v ./...
      - run: make test-ci
  deploy:
    working_directory: /go/src/github.com/hscasn/go-microservice
    docker:
      - image: circleci/golang:1.11
    steps:
      - checkout
      - run:
          name: Get dependencies
          command: go get -v ./...
      - run:
          name: Deploy
          command: |
            echo "Deploying..."
            ## Uncomment the line below to actually run
            ## the deployment script
            #make deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - test
      - deploy:
          requires:
              - test
          filters:
            branches:
              only:
                - master